### PR TITLE
#148 Support multiple export modules TOs

### PR DESCRIPTION
**Pull request by fax4ever**
Fixes (or at least it tries to fix) #148

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Thx, this LGTM. I know that tests are a bit sparse in ModiTect, did you have a chance to run this with your project/pom.xml, verifying that it does what it should do?

**Comment by fax4ever** [comment]
Hi @gunnarmorling. Thanks for the review!

Running the test locally it seems that, given the exports:
``` xml
<exports>
  org.hibernate.search.*.impl to org.hibernate.search.util.common, org.hibernate.search.engine, org.jboss.logging;
  *;
</exports>
```

ModiTect produces exports:
``` java
exports org.hibernate.search.engine.search.projection.dsl.impl to org.hibernate.search.util.common, org.hibernate.search.engine, org.jboss.logging;
...
exports org.hibernate.search.engine.search.sort.dsl.impl to org.hibernate.search.util.common, org.hibernate.search.engine, org.jboss.logging;
```

And I seems that it still works with a singleton module list.
I also tested on a test project: https://github.com/fax4ever/maven-play/tree/main/multi-release-jar.

**Comment by gunnarmorling** [comment]
Applied; thx, @fax4ever!

**Comment by fax4ever** [comment]
Thanks @gunnarmorling!

**Pull request merged**
