### PR TITLE
Update JReleaser configuration with changelog formatting options

### PR DESCRIPTION
**Pull request by aalmiray**

### CODE REVIEW

**Review by gunnarmorling — APPROVED** [review]

**Comment by gunnarmorling** [comment]
Rebased and applied. Thanks, @aalmiray! The failure was stemming from the fact that the POMs were still at 1.0.0.CR2 instead of -SNAPSHOT. Wondering whether this shouldn't be part of the release job, too?

**Comment by aalmiray** [comment]
Ah yes, likely. Wonder if we could use https://www.mojohaus.org/versions-maven-plugin/use-next-snapshots-mojo.html to figure out the number automatically.

**Comment by gunnarmorling** [comment]
Ah, yes, why not. I also wouldn't mind if it simply was another parameter to the trigger job.

**Comment by aalmiray** [comment]
I think kcctl already has something like that https://github.com/kcctl/kcctl/blob/93e60e967189642747f90b512668db46c0273a77/.github/workflows/release.yml#L19-L27

Except in this case both trigger and release are found in a single workflow file and share intermediate files using artifact upload/download.

**Pull request merged**
