### PR TITLE
Mark maven plugin goals @threadSafe

### LINKED ISSUE #95: Support multi-threaded Maven builds
Here is what Maven reports when invoked in multi-threaded mode (say, "mvn -T 9 clean install") when Moditect plugin is used:

[WARNING] The following plugins are not marked @threadSafe in Tascalate JavaFlow / Tools / Apache Maven:
[WARNING] org.moditect:moditect-maven-plugin:1.0.0.Beta2
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.

If Moditect is thread-safe by nature than it makes sense to add aforementioned annotation...

### PR DESCRIPTION
**Pull request by jfallows**
Fix #95.

I have reviewed the code for each `moditect plugin` goal and it seems as though they use project relative resources only, triggering no conflicts when running in a multi-threaded parallel build.

### CODE REVIEW

**Review by bmarwell — APPROVED** [review]

**Comment by aalmiray** [comment]
What does it mean for a plugin to be marked as `threadsafe`? The docs don't say much, do they?

AFAICT the `add-module-info` goal modifies the project's artifact by rewriting it. If another gal works on the same artifact at the same time, then there's no guarantee on the outcome, is there? Similarly, the `generate-module-info` goal could find itself in a similar position.

I don't think we can mark all ModiTect mojos as threadsafe.

**Comment by gunnarmorling** [comment]
> AFAICT the add-module-info goal modifies the project's artifact by rewriting it. If another gal works on the same artifact at the same time, then there's no guarantee on the outcome, is there?

Can this actually happen? IIUC, parallelism in Maven refers to building multiple modules concurrently, but not execute the goals of one module concurrently. I.e. if a plug-in can run safely for _different_ modules at the same time, it should be fine. There's some context [here](https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3).

**Comment by aalmiray** [comment]
Gotcha. If parallelism is executed per module as a whole, instead of per goals within a module then I think we're good to go and mark all mojos as threadsafe.

**Comment by gunnarmorling** [comment]
Yeah, at least I am not aware of any way for running the goals of one module in parallel.

**Comment by gunnarmorling** [comment]
Merged. Thx, @jfallows!

**Pull request merged**
