### PR TITLE
Support for '--no-header-files' and '--no-man-pages'

### PR DESCRIPTION
**Pull request by szediwy**
Simple modification to support '--no-header-files' and '--no-man-pages'.

### CODE REVIEW

**Comment by cbm64chris** [comment]
+1

**Comment by gunnarmorling** [comment]
Sorry, had missed this so far. LGTM, @szediwy! Could you also add the new options to the README file? Thanks!

**Comment by cbm64chris** [comment]
These options will only work for [JDK 11](https://docs.oracle.com/en/java/javase/11/tools/jlink.html) and above. They were introduced in 9 and changed in 11. We should probably call that out in the README.md changes you are making.

**Comment by gunnarmorling** [comment]
Applied. Thanks! Requiring JDK 11 is fine at this point, as 9/10 are EOL anyways.

**Pull request merged**
