### PR TITLE
#217 Configure JReleaser for deployments to Maven Central

### LINKED ISSUE #216: NullPointerException during create-runtime-image
NullPointerException experienced if the project artifact has not been created yet.

If you...
 - Skip the jar plugin (because the jar has been packed into a separate project)
 - create the image prior to assembling the jar (because it's being packed into the jar)
 - or other nonsense where the project lacks an artifact when moditect is invoked
...the build will fail on a NullPointerException.
Works fine in release 1.0.0.RC1

Caused by: java.lang.NullPointerException
    at org.moditect.mavenplugin.image.CreateRuntimeImageMojo.execute (CreateRuntimeImageMojo.java:126)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    ...

example pom:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>exmaple-sscce</groupId>
    <artifactId>moditect-image-npe-sscce</artifactId>
    <version>1.0.0</version>

    <build>
        <plugins>
            <plugin>
                <groupId>org.moditect</groupId>
                <artifactId>moditect-maven-plugin</artifactId>
                <version>1.0.0.Final</version>
                <executions>
                    <execution>
                        <id>generate-image</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>create-runtime-image</goal>
                        </goals>
                        <configuration>
                                <modulePath>
                                        <path>${project.build.directory}/modules</path>
                                </modulePath>
                                <modules>
                                <module>jdk.httpserver</module>
                                </modules>
                                <outputDirectory>
                                        ${project.build.directory}/jlink-image/slim-jre
                                </outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

### LINKED ISSUE #217: Update Maven deployment strategy
Use JReleaser instead of nexus-staging plugin

### PR DESCRIPTION
**Pull request by aalmiray**
@gunnarmorling the following GH secrets must be added to this repository

```
JRELEASER_NEXUS2_USERNAME
JRELEASER_NEXUS2_PASSWORD
JRELEASER_GPG_PASSPHRASE
JRELEASER_GPG_PUBLIC_KEY
JRELEASER_GPG_SECRET_KEY
```

Details at https://jreleaser.org/guide/latest/examples/maven/maven-central.html#_maven

Fixes #217

### CODE REVIEW

**Comment by bmarwell** [comment]
@aalmiray it should be 'fixes #217', not 216

**Comment by hboutemy** [comment]
@gunnarmorling please

**Comment by aalmiray** [comment]
As an alternative I could configure my credentials to push a release this weekend.

**Comment by hboutemy** [comment]
yes, please @aalmiray

**Comment by aalmiray** [comment]
Will have to release from a local environment as I don't have admin access to update CI settings.

**Comment by gunnarmorling** [comment]
Hey all, sorry for the late reply, things are a bit crazy here right now. I
have one more conference coming up next week, then it's gonna look better
again. Andres, how about we set this up some time next weekend?

Am So., 5. Nov. 2023 um 16:31 Uhr schrieb Andres Almiray <
***@***.***>:

**Comment by aalmiray** [comment]
@gunnarmorling Yes, of course :D

**Comment by aalmiray** [comment]
@gunnarmorling I'm sorry I messed up the release tag. I forgot that `.Final` is the preferred tag and thus `1.1.0` was released plain as I noticed the missing tag once deployment to Maven Central had finished.

**Comment by aalmiray** [comment]
@hboutemy please go ahead and test `1.1.0`. Sorry for the delay 😓

**Comment by hboutemy** [comment]
thank you
Jackson upgraded https://github.com/FasterXML/jackson-parent/commit/947b9c0ddd53cbe38c4c7262e18c52058306dc36 , now waiting for the next release to see the improvement

**Pull request merged**
